

CREATE TABLE zomato (
    orderid INT PRIMARY KEY,
    dishname VARCHAR(100),
    restaurent VARCHAR(100),
    quantity INT,
    orderdate DATE,
    amount DECIMAL(10,2),
    rating DECIMAL(2,1),
    city VARCHAR(100),
    deliverytime TIME,
    userid INT
);

INSERT INTO zomato (orderid, dishname, restaurent, quantity, orderdate, amount, rating, city, deliverytime, userid) VALUES
(1, 'Biryani', 'Paradise', 2, '2024-02-01', 500.00, 4.5, 'Delhi', '00:30:00', 101),
(2, 'Pizza', 'Dominos', 1, '2024-02-01', 300.00, 4.2, 'Mumbai', '00:45:00', 102),
(3, 'Burger', 'McDonalds', 3, '2024-02-02', 450.00, 4.0, 'Bangalore', '00:25:00', 103),
(4, 'Pasta', 'Olive Garden', 1, '2024-02-03', 350.00, 3.9, 'Pune', '00:40:00', 104),
(5, 'Dosa', 'Saravana Bhavan', 2, '2024-02-04', 200.00, 4.7, 'Chennai', '00:20:00', 105),
(6, 'Biryani', 'Bawarchi', 1, '2024-02-05', 280.00, 4.6, 'Hyderabad', '00:35:00', 106),
(7, 'Sushi', 'Wasabi', 1, '2024-02-06', 900.00, 4.8, 'Delhi', '00:50:00', 107),
(8, 'Sandwich', 'Subway', 2, '2024-02-07', 250.00, 4.0, 'Mumbai', '00:30:00', 108),
(9, 'Pav Bhaji', 'Shivsagar', 1, '2024-02-08', 180.00, 4.3, 'Ahmedabad', '00:25:00', 109),
(10, 'Ice Cream', 'Naturals', 3, '2024-02-09', 240.00, 4.5, 'Kolkata', '00:15:00', 110),
(11, 'Pizza', 'Dominos', 2, '2024-02-10', 600.00, 4.2, 'Delhi', '00:45:00', 101),
(12, 'Burger', 'Burger King', 1, '2024-02-11', 220.00, 4.1, 'Bangalore', '00:30:00', 102),
(13, 'Samosa', 'Haldiram', 4, '2024-02-12', 100.00, 4.0, 'Pune', '00:20:00', 103),
(14, 'Dhokla', 'Gwalia', 2, '2024-02-13', 150.00, 4.3, 'Ahmedabad', '00:25:00', 104),
(15, 'Tandoori Chicken', 'Barbeque Nation', 1, '2024-02-14', 700.00, 4.6, 'Mumbai', '00:50:00', 105),
(16, 'Chole Bhature', 'Bikanervala', 2, '2024-02-15', 250.00, 4.2, 'Delhi', '00:35:00', 106),
(17, 'Biryani', 'Paradise', 3, '2024-02-16', 750.00, 4.7, 'Hyderabad', '00:40:00', 107),
(18, 'Momos', 'Wow Momos', 4, '2024-02-17', 300.00, 4.1, 'Kolkata', '00:20:00', 108),
(19, 'Pasta', 'Olive Garden', 1, '2024-02-18', 350.00, 3.9, 'Pune', '00:40:00', 109),
(20, 'Vada Pav', 'Anand Stall', 2, '2024-02-19', 80.00, 4.5, 'Mumbai', '00:15:00', 110),
(21, 'Rolls', 'Kathi Rolls', 1, '2024-02-20', 120.00, 4.3, 'Delhi', '00:20:00', 101),
(22, 'Ice Cream', 'Baskin Robbins', 2, '2024-02-21', 280.00, 4.7, 'Bangalore', '00:15:00', 102),
(23, 'Pizza', 'Pizza Hut', 1, '2024-02-22', 350.00, 4.1, 'Mumbai', '00:45:00', 103),
(24, 'Chaat', 'Bikanervala', 3, '2024-02-23', 210.00, 4.0, 'Ahmedabad', '00:30:00', 104),
(25, 'Momos', 'Tandoori Momos', 2, '2024-02-24', 180.00, 4.2, 'Delhi', '00:25:00', 105),
(26, 'Biryani', 'Bawarchi', 1, '2024-02-25', 280.00, 4.6, 'Hyderabad', '00:35:00', 106),
(27, 'Noodles', 'Mainland China', 2, '2024-02-26', 400.00, 4.3, 'Pune', '00:45:00', 107),
(28, 'Paratha', 'Pind Balluchi', 2, '2024-02-27', 250.00, 4.0, 'Delhi', '00:25:00', 108),
(29, 'Idli', 'Saravana Bhavan', 3, '2024-02-28', 210.00, 4.4, 'Chennai', '00:20:00', 109),
(30, 'Dal Makhani', 'Punjabi Rasoi', 1, '2024-02-29', 380.00, 4.5, 'Mumbai', '00:35:00', 110),
(31, 'Pasta', 'Little Italy', 2, '2024-03-01', 400.00, 4.2, 'Bangalore', '00:40:00', 101),
(32, 'Soup', 'Mainland China', 1, '2024-03-02', 250.00, 4.1, 'Kolkata', '00:20:00', 102),
(33, 'Biryani', 'Paradise', 2, '2024-03-03', 500.00, 4.5, 'Delhi', '00:30:00', 103),
(34, 'Dosa', 'Saravana Bhavan', 1, '2024-03-04', 150.00, 4.7, 'Chennai', '00:20:00', 104),
(35, 'Pav Bhaji', 'Shivsagar', 2, '2024-03-05', 180.00, 4.3, 'Mumbai', '00:25:00', 105);


select * from zomato;

--Question 1
--Write a query to find the top 5 most ordered dishes 

select top 5 dishname,sum(quantity)as no_of_times_ordered from  zomato group by dishname order by sum(quantity) desc; 


--Question 2
--write a query to find the top 5 restaurents  from most order were oerdered

select top 5 restaurent,count(distinct(orderid)) as no_of_orders from zomato group by restaurent order by count(distinct(orderid)) desc;

--Question 3
--Write query to retrieve all orders placed in last 30 days for  a specific user

select distinct userid,dishname,restaurent from zomato where DATEDIFF(day,getdate(),orderdate)<=30 and userid=101;

--Question 4
--write a query to find the total revenue generated by all restaurent in the last month

select restaurent, sum(amount) as total_revenue from zomato WHERE FORMAT(orderdate, 'yyyy-MM') = FORMAT(DATEADD(MONTH, -1, '2024-03-03'), 'yyyy-MM')
 group by restaurent order by sum(amount) desc; --use getdate() to count from current date instead of '2024-03-03'

--Question 5
--write a query to retrieve the top 10 restaurent with the highest average customer rating

select restaurent ,format(avg(rating),'N1') as avg_rating from zomato group by restaurent order by avg(rating) desc


--Question 6
--write a query to list all customers who have ordered at least one dish from more than 3 different restaurents

select userid from zomato  group by userid having count(distinct(restaurent))>3

--Question 6
--Write a query to identify restaurents where the average order value is higher than over all average order value across all restaurents

with avgordervalue as( select restaurent, avg(amount) as averageordervalue from zomato group by restaurent),
overallAvg as (select avg(amount) as overallAverage from zomato)
select a.restaurent,a.averageordervalue from avgordervalue a ,overallAvg o where a.averageordervalue>o.overallAverage

--Question 7
--write a query to find the rank of each restaurent based on total revenue within each city

select restaurent,city,sum(amount) as total_revenue_city,   rank() over (partition by city order by sum(amount) desc ) as rank from zomato
group by restaurent,city order by rank

--Question 8
--cateogorize restaurent into high, medium and low revenue based on their monthly sales

with monthlyrevenue as( select restaurent, sum(amount) as totalmonthlyrevenue from zomato WHERE FORMAT(orderdate, 'yyyy-MM') = FORMAT(DATEADD(MONTH, -1, '2024-03-03'), 'yyyy-MM')
group by restaurent )
select restaurent,totalmonthlyrevenue ,
case when totalmonthlyrevenue>1000 then 'High Revenue'
when totalmonthlyrevenue between 600 and 1000 then 'Medium Revenue'
else 'Low Revenue'
end as Revenue_Category
from monthlyrevenue


--Question 9
--write a query to retrieve the top 5 restaurents with the fastest avg delivery time

select restaurent,cast(DATEADD(MINUTE, 
        AVG(DATEDIFF(MINUTE, '00:00:00', deliverytime)), 
        '00:00:00'
    ) as time) AS avg_delivery_time  from zomato group by restaurent

--question 10
 --calculate the contribution of  each city to the total revenue for a given year
 SELECT city, SUM(amount) AS total_revenue, YEAR(orderdate) AS year FROM zomato  WHERE YEAR(orderdate) = 2024  GROUP BY city, YEAR(orderdate);  

